### ISSUE TITLE
Partner update - add Empowerhack

### ISSUE THREAD

**Issue by krissy** [womenhackfornonprofits/whfnp#10]
Empowerhack logo missing from Our Partners section

**Comment by lili2311** [comment]
Link to logo? Or should I take the one form their site? I think it is just styled text.

**Comment by krissy** [comment]
![ehdark](https://cloud.githubusercontent.com/assets/574526/12991805/e4a46a5a-d108-11e5-8464-e838e0945cfd.png)

**Comment by krissy** [comment]
@lili2311 got the asset off them above :)

**Comment by lili2311** [comment]
https://github.com/womenhackfornonprofits/whfnp/pull/13
