### ISSUE TITLE
Newsletter section missing from some pages

### ISSUE THREAD

**Issue by krissy** [womenhackfornonprofits/whfnp#11]
From browsing, the Newsletter section has been omitted on the following pages:
- About
- Contact

**Comment by krissy** [comment]
Happy to add but confirming if this is on purpose or accidentally omitted first

**Comment by lili2311** [comment]
on purpose due to the alternating colours, can be added in but last section should be white on every page so add this in the css?

**Comment by tanyapowell** [comment]
@krissy and @lili2311 can this issue be closed?

**Comment by EChesters** [comment]
In terms of UX I think both of these pages would benefit from having the newsletter section on there. 

@lili2311 When you make a design decision can you clear it up before going ahead and omitting sections :) 

I've done the templating for these pages so later this week I'll add them in a re-push. I'll change this to in progress and keep it open for now.

**Comment by EChesters** [comment]
Will be fixed by:
https://github.com/womenhackfornonprofits/whfnp/pull/109
and
https://github.com/womenhackfornonprofits/whfnp/pull/104

**Comment by EChesters** [comment]
This has been fixed by the 2 previous PRs mentioned, which have been merged.
