### ISSUE TITLE
Broken link for Meet the Volunteers CTA on homepage 

### ISSUE THREAD

**Issue by krissy** [womenhackfornonprofits/whfnp#12]
![screen shot 2016-02-11 at 22 38 17](https://cloud.githubusercontent.com/assets/574526/12993130/52eb3190-d110-11e5-9d18-d3bfeb38bbb1.png)

Currently linking to meet-the-volunteers.html

**Comment by krissy** [comment]
Happy to fix but confirming if this is supposed to link to volunteers.html or jump to a #meet-the-volunteers target on the Volunteers page?

**Comment by lili2311** [comment]
https://github.com/womenhackfornonprofits/whfnp/pull/13
