### ISSUE TITLE
Events page image too low quality

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#121]
http://www.womenhackfornonprofits.com/events.html

We need to find a better image to use here and replace it. @Nandhini31 do we have any images at our disposal to use? Alternatively are you ok with using stock images from unsplash?

**Comment by tanyapowell** [comment]
This was resolved with #63 and just needs deploying to the live production site

**Comment by lili2311** [comment]
Okies, closing the issue.
