### ISSUE TITLE
Create a board image for Eli

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#125]
- Get an image form ELi she would like for the board page
- Create the exact same dimension image as the others, use the original psd/sketch file

**Comment by elischutze** [comment]
![eli](https://cloud.githubusercontent.com/assets/5872126/17696862/1b4bc066-63a9-11e6-8ec6-46c72db9ece2.JPG)

**Comment by herecomesjaycee** [comment]
@lili2311 waiting for the png from sketch file :) last item on #126 before I make a pull request

**Comment by lili2311** [comment]
yep sorry will try to upload it tonight!

**Comment by herecomesjaycee** [comment]
If you send me the sketch file, I can do it tonight. I know Sketch and I
have a copy of the app :)

**Comment by lili2311** [comment]
Great I will add the sketch file here: https://github.com/womenhackfornonprofits/whfnp/tree/dev/raw_assets please commit the updated version once done as well.

**Comment by herecomesjaycee** [comment]
![image](https://cloud.githubusercontent.com/assets/13175171/18108185/07706aaa-6f03-11e6-8866-220ee7ce521e.png)

Please review and the git commit ref 1320d9bf860b744b44d4a795cd5766741e8be908

**Comment by elischutze** [comment]
is there an "adorable" tag for issues? 🤔

**Comment by herecomesjaycee** [comment]
😘🤗💁
