### ISSUE TITLE
📝 Board Members need updating

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#126]
We have some new board members that need adding to the website and some have left.
- Add Eli to the board member page (need to request image and make it in the shape of others first, [ticket here](https://github.com/womenhackfornonprofits/whfnp/issues/125))
- Add Raquel to the board member page (image already on site, check the volunteer page use that one)
- Get a link for Eli she would like her image to link to
- Get a link for Raquel she would like to link to
- Remove Tanya, Funmi & Corinne
- Remove the "boards names" currently there are no boards just board members that cover everything.

**Comment by herecomesjaycee** [comment]
I'll be working on this ticket @herecomesjaycee

**Comment by herecomesjaycee** [comment]
![image](https://cloud.githubusercontent.com/assets/13175171/18108131/d97447c0-6f02-11e6-8a45-982a653f3402.png)

Please review
