### ISSUE TITLE
Project images are not properly centered on mobile 

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#131]
Add a `background: url(images/bg.jpg) no-repeat center center;` to fix the issue to all project images and test on mobile to ensure the image is still responsive but is centred on mobile.

**Comment by VAO11** [comment]
@lili2311 I tried to apply the suggested change but  don't notice any change. Can this issue be closed as it is fixed when the page is updated to bootstrap?

**Comment by VAO11** [comment]
Resolved by PR #150
