### ISSUE TITLE
Add all current projects to the projects page

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#133]
# Overview

Add all current projects in the same format as the existing ones to the website.
If possible get a project screenshot, if the project is too early stages let's discuss here a suitable replacement image per project. Usually a logo of the non profit or similar would be great.
## To Do:
- [x] Add together in the UK project, content can be found below
- [x] Update Pimp My Cause project, content can be found below

_updated 24/10/2016_
- [ ] Add OCD Action project, content can be found below
- [ ] Add earthlinks project, early stages need more information
- [ ] Add Novaledge project, early stages need more information

**Comment by lili2311** [comment]
# Together in the UK Project

Image:
![screen shot 2016-10-06 at 22 24 54](https://cloud.githubusercontent.com/assets/2911613/19171761/642563c4-8c16-11e6-9203-bee7743c96cf.png)

## Description

TGIUK is a space for people who have come from outside the UK to live and work here. A space where people can share their insights and stories and engage with others about their future. The organisation aims to help those new to the UK to settle in and become more familiar with the UK culture and customs. Project is to help TGIUK with design of a professional site that will clearly show their purpose, be inviting and create momentum.

## Stack:

Wordpress, CSS, HTML

## Links:

GitHub: https://github.com/womenhackfornonprofits/together-in-the-uk 
Site: https://www.togetherintheuk.co.uk

**Comment by lili2311** [comment]
# Pimp My Cause

Image:
![screen shot 2016-10-06 at 22 22 54](https://cloud.githubusercontent.com/assets/2911613/19171912/1789b6e0-8c17-11e6-8d65-9979c5ce538e.png)

## Everything else

same

**Comment by VAO11** [comment]
Am I replacing the pimp my cause image or adding a new file and pointing to the new file?

**Comment by lili2311** [comment]
yes please replace, what about the other projects?

**Comment by lili2311** [comment]
Other projects don't have anything to link to just yet will add soon.
