### ISSUE TITLE
Project Text needs to be better positioned next to image

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#135]
**Currently the title is misaligned with the image:**
![screen shot 2016-08-19 at 19 07 12](https://cloud.githubusercontent.com/assets/2911613/17819644/c2011e4e-6640-11e6-8266-55101c754ed4.png)
# TO DO
- [ ] Please align the image and project title exactly, like so:
  ![screen shot 2016-08-19 at 19 10 57](https://cloud.githubusercontent.com/assets/2911613/17819645/c208a8c6-6640-11e6-99bd-010b0911a2a3.png)
- [ ] Please give the projects some margin top to make it sit a little further aways from the page title
- [x] change the page title to be h1 not h2.

**Comment by VAO11** [comment]
Hi, I think this has been resolved as part of issue #148. PR #151
