### ISSUE TITLE
Non Profit Page should be converted to use bootstrap grid like other pages

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#136]
# Issue

![screen shot 2016-08-19 at 19 19 35](https://cloud.githubusercontent.com/assets/2911613/17819911/1e996b88-6642-11e6-8962-8fcb6b70747a.png)
![screen shot 2016-08-19 at 19 19 55](https://cloud.githubusercontent.com/assets/2911613/17819912/1e9d8344-6642-11e6-8b5a-6a111a88181c.png)
# TO DO
- [x] Use bootsrap grid to fix the layout issue, remove the col-2 custom column code and convert to use bootsrap, check other pages for an example.
- [x] Make the columns look good on mobile they should take up all 12 cols on mobile
- [x] On desktop each half should be 6 cols or less but centered in the page
- [x] The whole page should only be using boostrap remove all col2 col3 classes that were hand coded

**Comment by herecomesjaycee** [comment]
![screen shot 2016-09-18 at 14 55 17](https://cloud.githubusercontent.com/assets/13175171/18616321/9e51a9c2-7db1-11e6-9df9-fe353b3542f6.png) - Mobile view
![screen shot 2016-09-18 at 14 54 56](https://cloud.githubusercontent.com/assets/13175171/18616322/9e5451c2-7db1-11e6-9d45-65eb772b470b.png) - Desktop view

**Comment by VAO11** [comment]
Nice jaycee. Looks really good.
