### ISSUE TITLE
Test the website on Firefox

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#138]
Test the development site:http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/index.html on Firefox browser. 
- [x] Check that nothing looks broken, things do not overlap anywhere
- [x] Check the layout of all pages looks the same as on Chrome browser, make sure there are no layout issues
- [ ] Check you cannot submit forms with missing mandatory/required info
- [ ] Try to generate errors when submitting a form, does an appropriate error show?

**Comment by suganya-s** [comment]
[nonprofits page](http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/non-profits.html) has a Volunteer FAQ button, that also doesn't lead to an FAQ page

![image](https://cloud.githubusercontent.com/assets/11741177/19166143/5cb0706a-8bfe-11e6-9ebe-8745bf29ceff.png)

**Comment by suganya-s** [comment]
One-line input fields don't render very well, e.g. on [this page](http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/volunteer-contact.html)

![image](https://cloud.githubusercontent.com/assets/11741177/19166824/0ee5ab04-8c01-11e6-95aa-27462effa8c6.png)

Fixed the issue

**Comment by lili2311** [comment]
Fixed the form not being centered >> http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/volunteer-contact.html

Fixed FAQ Link
http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/non-profits.html

Need to check the form not loading the numbers correctly

**Comment by lili2311** [comment]
All issues fixed now on latest deploy, closing
