### ISSUE TITLE
Test the website in Safari

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#139]
Test the development site: http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/index.html on Safari browser. 
- [ ] Check that nothing looks broken, things do not overlap anywhere
- [ ] Check the layout of all pages looks the same as on Chrome browser, make sure there are no layout issues
- [x] Check you cannot submit forms with missing mandatory/required info
- [ ] Try to generate errors when submitting a form, does an appropriate error show?

**Comment by Emilianas** [comment]
![screen shot 2016-09-08 at 10 56 47](https://cloud.githubusercontent.com/assets/20131617/18345394/3126c540-75b3-11e6-909b-ca3831a57719.png)

**Comment by Emilianas** [comment]
![screen shot 2016-09-08 at 11 03 33](https://cloud.githubusercontent.com/assets/20131617/18345539/e0c84e74-75b3-11e6-8d3a-c9c065801b1c.png)
The WHFNP link at the top of the page is not working

**Comment by lili2311** [comment]
@Emilianas  please could you create each issue as a separate ticket here? Also no need to test blog.womenhackfornonprofits.com as it is Medium we do not have our own built blog.

**Comment by lili2311** [comment]
Please for each issue, mention how to replicate:
1. Link
2. Size of the webpage at the time you see the issue
3. Steps to replicate

**Comment by Emilianas** [comment]
The WHFNP icon (next to Elizabeth's article) looks like a link but it's not working

**Comment by Emilianas** [comment]
Oh... I need some help with that
1. Link?
2. Where do I find the size of the webpage?
3. Replicate?

**Comment by Emilianas** [comment]
Cool, I shall not go beyond the WHFNP website.

**Comment by lili2311** [comment]
No worries for first example above:
1. Link is: http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/about.html
2. Screen size: 
- right click on the page
- click Inspect
- You can now resize the whole page or even just use the little icon that looks like table/phone at the top which will resize the page to some common device screen sizes. If the issue occurs for ALL, just mention ALL screensizes.
1. Replicate: what did you do (exact steps) in order ot be able to see the problem, if you have just loaded the page and problem is visible just say that. If you filled out a form and during filling out you Name the issues occurred just mention that. Imagine we have to try and find where the screenshot has come from and how did you get the issue to display itself otherwise we can't tell what needs fixing.

**Comment by Emilianas** [comment]
I'm testing it on Safari and can't see the Inspect with a right click, I have resized it with cmd+/cmd- and Eli's photo still doesn't load.

**Comment by lili2311** [comment]
Yep sorry in Safari it is also Right Click -> Inspect Element, the image not loading is becoe it did not deploy. So it will be like that for all, so just open an issue that says "Deploy the image for Eli for page X" with a screenshot.

**Comment by Emilianas** [comment]
![screen shot 2016-09-08 at 11 29 05](https://cloud.githubusercontent.com/assets/20131617/18346311/72094db8-75b7-11e6-9172-89920bb3311e.png)

**Comment by Emilianas** [comment]
1. http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/about.html
2. All sizes 
3. Just loaded the page and problem is visible.
   ![screen shot 2016-09-09 at 18 14 28](https://cloud.githubusercontent.com/assets/20131617/18396038/728d066e-76b9-11e6-86ce-3c6dc2e0b4bd.png)

**Comment by Emilianas** [comment]
As on iPhone, on Safari, the form Let's connect! also takes me to a confirmation page.
![screen shot 2016-11-04 at 23 00 15](https://cloud.githubusercontent.com/assets/20131617/20025047/acf45eba-a2e2-11e6-8bd8-b1077db2c132.png)
![screen shot 2016-11-04 at 22 59 23](https://cloud.githubusercontent.com/assets/20131617/20025050/b0687a04-a2e2-11e6-9b3e-253ba31f6194.png)

**Comment by lili2311** [comment]
Confirmation page should no loner show, that is to allow form submition, please retest form submition? 

We do not do any validation on correct email addresses right now and haven't done before. It has not caused any issues so far. So we probably wont bother fixing just yet and trust the user to enter a correct email address.
