### ISSUE TITLE
Test the website in Internet Explorer 10

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#140]
Test the development site: http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/index.html on Firefox browser. 
- [x] Check that nothing looks broken, things do not overlap anywhere
- [x] Check the layout of all pages looks the same as on Chrome browser, make sure there are no layout issues
- [x] Check you cannot submit forms with missing mandatory/required info
- [x] Try to generate errors when submitting a form, does an appropriate error show?

**Comment by lili2311** [comment]
any issues found?

**Comment by VAO11** [comment]
Logo look stretched on IE11
![ie11_logo_stretched](https://cloud.githubusercontent.com/assets/20387843/20252720/97dc69c8-aa1c-11e6-830a-77eb6ebddf0c.PNG)

**Comment by VAO11** [comment]
The three columns should be contained like the Volunteers page and live site:
![ie11_np_w2expect](https://cloud.githubusercontent.com/assets/20387843/20252727/b20add3e-aa1c-11e6-9db2-2cb44f1ba791.PNG)

This is not IE specific but across the browsers

**Comment by VAO11** [comment]
The contact us page Bootstrap Grid settings need to be amended to match those on the volunteers page as currently dues not resize correctly. 

_current view:_
![ie11_form_section_bsgrid_settings1](https://cloud.githubusercontent.com/assets/20387843/20252910/58d11a88-aa1e-11e6-9634-378d881b09f7.PNG)

_These setting fix the issue:_
![ie11_form_section_bsgrid_settings](https://cloud.githubusercontent.com/assets/20387843/20252845/ce67a4d4-aa1d-11e6-9a74-8a43af0a37ca.PNG)

_This is not browswer specific but across all browsers._

**Comment by VAO11** [comment]
white margin identified in #143 has disappeared on desktop IE, Firefox and chrome browsers. Also tested on Samsung S6 edge (native, chrome and firefox browsers) and the margin is no longer there. I think this has been fixed.

**Comment by lili2311** [comment]
all fixed 🎉
