### ISSUE TITLE
Make the homepage partner logos the same height

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#141]
- [x] Change the height of the logos to be 4em 
- [x] Change the width of the logos to be `auto`.

They should look more like this:
<img width="927" alt="screen shot 2016-08-23 at 14 57 35" src="https://cloud.githubusercontent.com/assets/2911613/17894670/0af77e96-6942-11e6-9b40-9d051c07d285.png">

**Comment by elizabethvenner** [comment]
Logos have been resized.

**Comment by lili2311** [comment]
is there a Pull Request we can review?
