### ISSUE TITLE
Test the website on an iPad

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#143]
Test the development site: http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/index.html on iPad device (please pm Lili if you need access to browserstack for testing). 
- [x] Check that nothing looks broken, things do not overlap anywhere
- [x] Check the layout of all pages looks the same as on Chrome browser, make sure there are no layout issues
- [x] Check you cannot submit forms with missing mandatory/required info
- [x] Try to generate errors when submitting a form, does an appropriate error show?

**Comment by Emilianas** [comment]
Just browsing on the iPad, a white margin on the right side ![img_0002](https://cloud.githubusercontent.com/assets/20131617/20004717/d663b172-a285-11e6-9783-c8a6d60b4694.PNG)

**Comment by Emilianas** [comment]
Browsing, images appear incomplete ![img_0003](https://cloud.githubusercontent.com/assets/20131617/20004802/41852968-a286-11e6-9f2c-7ddc1e446f5a.PNG)

**Comment by lili2311** [comment]
images on project page being fixed and will be deployed today

**Comment by lili2311** [comment]
please confirm if the white margin is still there?

**Comment by Emilianas** [comment]
Yes, white margin still present on About and Non-Profits pages

**Comment by Emilianas** [comment]
No change on the Projects page, the images are still cut/incomplete.

**Comment by Emilianas** [comment]
The link to view open source project takes me to an empty repository for Jaspal's voice.
![screen shot 2016-11-15 at 18 22 56](https://cloud.githubusercontent.com/assets/20131617/20318074/b2a178f8-ab60-11e6-86d5-e0eabaf95bd6.png)

**Comment by VAO11** [comment]
Hi Amelia, I think you need to clear your cache as this has updated. When I first tested it, it looked like it had not updated but once I closed all my browsers and opened it

**Comment by Emilianas** [comment]
I'll open a private session on the iPad and try again @VAO11

**Comment by Emilianas** [comment]
You are right @VAO11 changes have taken place, no more white margin on any of the pages and the incomplete images from the projects page are gone.

**Comment by Emilianas** [comment]
The link from Jaspals Voice, View Open Source Project button still takes me to an empty repository, same on MacBook and iPhone.

**Comment by VAO11** [comment]
It is an empty repository. @lili2311 should  the link below removed?

**Comment by Emilianas** [comment]
The Jaspals-voice-app seems busy, could that be used?

**Comment by lili2311** [comment]
removed jaspals voice link, images should be all fixed now might need to open a new icognito session to see the changes
