### ISSUE TITLE
volunteers.html and non-profits.html  Page should be converted to use bootstrap grid like other pages 

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#146]
TO DO:
- [x] Convert both non-profits.html  and volunteers.html to use bootsrap grid to fix the layout issue, remove the col-2 custom column code and convert to use bootsrap, check other pages for an example.
- [x]  Make the columns look good on mobile they should take up all 12 cols on mobile
- [x]  Make the columns look good on desktop
- [x]  The whole page should only be using boostrap remove all col2 col3 classes that were hand coded

**Comment by herecomesjaycee** [comment]
Desktop view <img width="1233" alt="screen shot 2016-10-02 at 14 13 26" src="https://cloud.githubusercontent.com/assets/13175171/19020811/bf602b80-88aa-11e6-894e-f91e8e8e99e2.png">
<img width="1216" alt="screen shot 2016-10-02 at 14 13 40" src="https://cloud.githubusercontent.com/assets/13175171/19020813/bf606ed8-88aa-11e6-83b0-d48561a82208.png">
<img width="1256" alt="screen shot 2016-10-02 at 14 13 53" src="https://cloud.githubusercontent.com/assets/13175171/19020812/bf602fa4-88aa-11e6-98f6-2cad2440298e.png">
