### ISSUE TITLE
Convert the projects.html to use bootsrap grid

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/whfnp#148]
# TO DO
- [x] Use bootsrap grid instead of custom classes
- [x] Mobile 1 column layout
- [x] On desktop 2 column layout 
- [x] Remove the unused code from custom classes (the layout code), remove any media queries associated with this page once all moved to bootstrap.

**Comment by VAO11** [comment]
Th
![whfnp_projs-completed_ 148](https://cloud.githubusercontent.com/assets/20387843/19630101/65e6b7a4-997b-11e6-947b-0f96b57077e1.PNG)
