### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 (HTTP/2.0 400)

### ISSUE THREAD

**Issue by Emilianas** [womenhackfornonprofits/whfnp#152]
![screen shot 2016-10-06 at 19 44 40](https://cloud.githubusercontent.com/assets/20131617/19165883/774b662e-8bfd-11e6-994f-aa24bc07602d.png)
Just loading the page on Safari

**Comment by Emilianas** [comment]
It happens on all the user agents and all the pages of the website.

**Comment by Emilianas** [comment]
On loading all the pages
![screen shot 2016-10-12 at 22 15 24](https://cloud.githubusercontent.com/assets/20131617/19328384/4afe83e4-90cb-11e6-8dbc-b1f99e34756a.png)
![screen shot 2016-10-12 at 22 15 50](https://cloud.githubusercontent.com/assets/20131617/19328383/4aebd154-90cb-11e6-8619-f26b202293e9.png)

**Comment by VAO11** [comment]
Need to update the screen.scss google font url link for Open Sans to: 
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,300,700);

**Comment by VAO11** [comment]
Resolved by PR #160
