### ISSUE TITLE
Testing (iPhone)

### ISSUE THREAD

**Issue by Emilianas** [womenhackfornonprofits/whfnp#153]
On iPhone the text seems at points different, on the volunteers page, I don't know if it's on purpose or it is a bug.
![img_0002](https://cloud.githubusercontent.com/assets/20131617/19166625/28d6eba0-8c00-11e6-94e8-7c30f0964e95.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/20131617/19166631/2e3948ae-8c00-11e6-9cb4-4aca6c72fba8.PNG)
![img_0003](https://cloud.githubusercontent.com/assets/20131617/19166633/2fd5e33e-8c00-11e6-8455-d4687ea34f6e.PNG)

**Comment by Emilianas** [comment]
In "Want to know more?" the text seems to have a wider margin compared to the rest

![img_0173](https://cloud.githubusercontent.com/assets/20131617/20006828/4893fd78-a291-11e6-872d-8237a5b87b79.PNG)

**Comment by Emilianas** [comment]
On the Non-Profits page, the Let's connect! form
![img_0178](https://cloud.githubusercontent.com/assets/20131617/20024964/fe1521ea-a2e1-11e6-90b4-1c7aea202dd0.PNG)
![img_0175](https://cloud.githubusercontent.com/assets/20131617/20024966/01ab4582-a2e2-11e6-93e6-8a3bb024c3c7.PNG)

The form works without must info.

**Comment by Emilianas** [comment]
There seems to be a white margin on the right side and none on the left side, on the Non-Profits page.
![img_0174](https://cloud.githubusercontent.com/assets/20131617/20025312/136c0826-a2e5-11e6-908b-903086d19157.PNG)
![img_0177](https://cloud.githubusercontent.com/assets/20131617/20025313/13714ca0-a2e5-11e6-90a3-e764d4f3701a.PNG)

**Comment by Emilianas** [comment]
Extra white margin on some of the pages, only on the right side: About, Volunteers, Non-Profits.
![img_0001](https://cloud.githubusercontent.com/assets/20131617/20031056/cf94cdba-a369-11e6-950d-14935662bf15.PNG)
![img_0002](https://cloud.githubusercontent.com/assets/20131617/20031058/cfac9364-a369-11e6-8f81-d613a491c82f.PNG)
![img_0003](https://cloud.githubusercontent.com/assets/20131617/20031059/cfadb9b0-a369-11e6-866a-98392e77c356.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/20131617/20031061/cfae8d72-a369-11e6-99b9-e0804f98e6a0.PNG)
![img_0005](https://cloud.githubusercontent.com/assets/20131617/20031060/cfadc266-a369-11e6-9ead-4feebb8f24cf.PNG)
![img_0006](https://cloud.githubusercontent.com/assets/20131617/20031062/cfaf892a-a369-11e6-9af4-55a0b0011ba3.PNG)
![img_0008](https://cloud.githubusercontent.com/assets/20131617/20031057/cfa58182-a369-11e6-8a83-b0d51b2e5f00.PNG)
![img_0009](https://cloud.githubusercontent.com/assets/20131617/20031063/cfb61c54-a369-11e6-8ff5-280566363fe0.PNG)

**Comment by Emilianas** [comment]
Overlapping buttons on the Projects page.
![img_0011](https://cloud.githubusercontent.com/assets/20131617/20031124/9e88d526-a36a-11e6-9403-a61bf991ce61.PNG)
![img_0012](https://cloud.githubusercontent.com/assets/20131617/20031125/9e9d1a5e-a36a-11e6-9a06-b500c15a9c26.PNG)
![img_0013](https://cloud.githubusercontent.com/assets/20131617/20031127/9ea30a68-a36a-11e6-91f8-fe15278f0af7.PNG)
![img_0014](https://cloud.githubusercontent.com/assets/20131617/20031126/9e9db28e-a36a-11e6-9705-3fea5add1137.PNG)

**Comment by Emilianas** [comment]
Inconsistent text alignment on the Projects page and Events page
![img_0022](https://cloud.githubusercontent.com/assets/20131617/20031373/4fef990a-a36e-11e6-9c84-a65d30df9a80.PNG)
![img_0021](https://cloud.githubusercontent.com/assets/20131617/20031374/500747bc-a36e-11e6-88f2-98c6e9f36c8b.PNG)

**Comment by lili2311** [comment]
Text is no longer like this, please hard refresh >> http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/volunteers.html

Buttons fix is coming in a few minutes.

**Comment by lili2311** [comment]
http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/projects.html
