### ISSUE TITLE
Button incomplete on Contact Us

### ISSUE THREAD

**Issue by Emilianas** [womenhackfornonprofits/whfnp#158]
On full zoom when mouse on it ![screen shot 2016-10-12 at 22 18 10](https://cloud.githubusercontent.com/assets/20131617/19328133/3a826d92-90ca-11e6-9bc6-c7b55ba7ed79.png)
On mobile ![img_0040](https://cloud.githubusercontent.com/assets/20131617/19328266/c3a6273a-90ca-11e6-8c4e-531b84a6041e.png)

**Comment by lili2311** [comment]
what screensize is this? you zoomed in yourself right? If there is not enough space on a page there is nothing we can do. But if this is a device we can fix it.

**Comment by Emilianas** [comment]
The first image is on desktop at full zoom.
Second image is a screenshot on my iPhone, just browsing (no zooming)

**Comment by Emilianas** [comment]
I just had another look and it still looks the same

**Comment by lili2311** [comment]
okies ty! will fix tonight

**Comment by lili2311** [comment]
fixed >> http://devwomenhackfornonprofits.s3-us-west-2.amazonaws.com/projects.html
