### ISSUE TITLE
Non-Profits Page Bugs

### ISSUE THREAD

**Issue by VAO11** [womenhackfornonprofits/whfnp#159]
- [ ] FindACure Logo is below FindACure speech bubble on Mobile. This is should be above the FindACure Text Speech bubble like the PimpMyCause

Use Push And Pull - Change Column Ordering - http://www.w3schools.com/bootstrap/bootstrap_grid_examples.asp

![non-profit-bug](https://cloud.githubusercontent.com/assets/20387843/19585408/1dbc13f4-9744-11e6-95e1-35f28b566dfe.PNG)

**Comment by lili2311** [comment]
https://github.com/womenhackfornonprofits/whfnp/pull/166
