### ISSUE TITLE
page doesn't load at all

### ISSUE THREAD

**Issue by ck1ldn** [womenhackfornonprofits/whfnp#164]
First time i've ever done this, hope its right and helps 
Using a PC
Windows 7
latest Version Chrome
04/11/16
time: 21:16pm GMT
![image](https://cloud.githubusercontent.com/assets/13010623/20022715/c47b791a-a2d3-11e6-9104-6252d4c595af.png)

**Comment by VAO11** [comment]
Hi, can you please try again? I was able to access the site without any issues.

**Comment by ck1ldn** [comment]
Hi,
22.04
and able to gain access
