### ISSUE TITLE
Increase font weight

### ISSUE THREAD

**Issue by EChesters** [womenhackfornonprofits/whfnp#19]
Even on a retina display the text with font-weight: 100 is really hard to read, especially on the brighter colours.

Font weight needs to be increased to 200 for it to be readable.

**Comment by lili2311** [comment]
screenshot please? Is it the volunteer names? that is the only 100 i think

**Comment by EChesters** [comment]
It's everywhere, navbar, paragraph text, buttons, footer. Nowhere should have 100 font-weight. 

<img width="1680" alt="screen shot 2016-02-14 at 12 07 57" src="https://cloud.githubusercontent.com/assets/2605703/13033581/e7133494-d313-11e5-9f7c-4449fe35852f.png">

**Comment by lili2311** [comment]
Fixed in this [PR](https://github.com/womenhackfornonprofits/whfnp/pull/18)

**Comment by EChesters** [comment]
Font weight has now been changed to 400 rather than 200 mentioned in first comment: 

>   Fonts changed from 100 to 400, fixed icon

Can this be changed to font-weight: 200; please?

**Comment by lili2311** [comment]
across all?

**Comment by EChesters** [comment]
Just for the text was 100 previously.

**Comment by lili2311** [comment]
Just p text? or nav as well? or heading, p and nav?

**Comment by EChesters** [comment]
For everything that's not a header, 
navbar, paragraph text, buttons.
