### ISSUE TITLE
Placeholder text in forms is not easily readable

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp#21]
The font colour for the placeholder text doesn't stand out enough and could be hard for visually impaired people to read 

![image](https://cloud.githubusercontent.com/assets/11095605/13105719/865be718-d55c-11e5-8b2f-04098226c70e.png)

**Comment by EChesters** [comment]
Labels should always be outside of the input fields, with an additional placeholder of what format or an example of the information we need.

Labels should also be above the field, so the user's eyes don't have to flick from left to right, they just read straight down:

Name:
|___________________________|

Like so ^^^

**Comment by tanyapowell** [comment]
There aren't any labels on _this_ form. Only placeholders.

Worth checking all forms (in case there are some with labels) and then raising a Jira ticket to get labels added to all forms (I'm assuming no form on the site has labels) and get them added for release 2

**Comment by EChesters** [comment]
It's a "design" to put the labels (as placeholders) inside the text fields. Placeholders should be an example, not the name of the label that should be there. 

I agree that this needs to be consistent across all forms on the website, not sure if we actually do have any others. Our process is still emailing at the moment.

**Comment by lili2311** [comment]
There are labels too but hidden from view.  This is a common design/practice across many website, I can set the normal labels back.
