### ISSUE TITLE
Drop down shadows removed from images and buttons

### ISSUE THREAD

**Issue by EChesters** [womenhackfornonprofits/whfnp#22]
The harsh shadow on buttons such as on contact and on the project images needs to be removed:
![image](https://cloud.githubusercontent.com/assets/2605703/13106012/f978c6f2-d55d-11e5-88b7-1e30d292b3bf.png)

<img width="567" alt="screen shot 2016-02-17 at 10 05 53" src="https://cloud.githubusercontent.com/assets/2605703/13106035/155103e4-d55e-11e5-8590-e15ca8063bbd.png">

This isn't consistent across all images on the site, or buttons and has an old-timey website feel to it.

**Comment by tanyapowell** [comment]
@EChesters any suggestions for the find a cure image?

**Comment by EChesters** [comment]
There is nothing wrong with the project image, it's just the image that I chose for a screnshot. The grey shadow and border around _all_ of the images is what needs to be removed. The same border is on the contact button which is why that's there, it also needs to be removed.

**Comment by tanyapowell** [comment]
You didn't see the comment in [PR #28](https://github.com/womenhackfornonprofits/whfnp/pull/28) before it was merged. Have a read through the comments and you'll see what was said about it. 

Essentially all the changes above have been changed, but there's another issue

**Comment by lili2311** [comment]
Closing issue, open a new one if needed
