### ISSUE TITLE
Spacing on Volunteers page needs adjusting

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp#24]
**Device:** iPhone 6s
**Browser/Version:** Chrome V48.0.2564.104 & Safari

The spacing on the volunteers page is inconsistent. There's too much space between `Meet Our Volunteers` and the first testimonial. Then all the testimonials are cramped together _(2nd image)_

**Too much spacing compared to the 2nd image**
![image](https://cloud.githubusercontent.com/assets/11095605/13108478/19153c4a-d56b-11e5-8bfd-93cd40d3b6bd.png)

**Not enough spacing**
![image](https://cloud.githubusercontent.com/assets/11095605/13108480/2108de34-d56b-11e5-8fd7-972572bbc3a9.png)

**Comment by lili2311** [comment]
This page is missing volunteer images, will fix in next PR.
