### ISSUE TITLE
Repeated View Site/View Project links/buttons on Projects Page

### ISSUE THREAD

**Issue by EChesters** [womenhackfornonprofits/whfnp#29]
Links like 'read more', and repeated 'View Site' or 'View Project' cause issues with screen-readers as you  don't have context on what you're actually viewing. Often they scan by links only for relevance of page.

Each link must be unique and mention which project you are clicking to view. Example was in the original mockup as shown below:
<img width="647" alt="screen shot 2016-02-19 at 09 17 26" src="https://cloud.githubusercontent.com/assets/2605703/13171251/a51d1332-d6e9-11e5-8b85-0bc9f7e06922.png">

Actual: 
<img width="942" alt="screen shot 2016-02-19 at 09 18 16" src="https://cloud.githubusercontent.com/assets/2605703/13171268/ba2b7f02-d6e9-11e5-9a46-49ad4700169e.png">

**Why**
 When people use a screen-reader they can request a list of all links on the page. At the moment ours will look like this:
"View Project"
"View Project"
"View Project"
"View Site"
"View Site"

We need to add in which project like so:
"View the Pimp My Cause project"
"View the Jaspal's Voice site"

**Comment by EChesters** [comment]
**This only involves the text of the button - not the styling.**

**Comment by lili2311** [comment]
@tanyapowell can you also change the banner heading in non-profits-contact.html to say Non-Profts Contact Form?
