### ISSUE TITLE
Hero images quite dark

### ISSUE THREAD

**Issue by marizoldi** [womenhackfornonprofits/whfnp#42]
The hero images are quite dark. Perhaps it would be better a bit lighter.

**Comment by tanyapowell** [comment]
@marizoldi is it all images or specific images?

**Comment by EChesters** [comment]
It's the gradient overlaying the images. Some of the images ideally need to be changed as well, especially the pixelated ones, and try using some of the brighter pictures we have: 

**Images to change**
- About 
- Contact 
- Events

**Comment by lili2311** [comment]
Pixelated images have been changed by Tanya in a recent PR. This should be in Development. The gradient is an outstanding one.

**Comment by EChesters** [comment]
We need to deploy quicker, now I remember that was done a long while ago. The images still nmay need to be changed because they're quite beige. @tanyapowell has much more colourful images to use, which may or may not be impacted by the gradient. It works for a few images at the moment.

**Comment by tanyapowell** [comment]
I only changed the images on 
- Contact
- Events

The original image used for `about.html` is not mine.

If all the images are appearing beige and dark, then there is probably something in the code that is reducing the saturation and the gradient is masking the contrast.

Let's take off the gradient for all images and see what's happening underneath
