### ISSUE TITLE
Unable to navigate to sponsors websites

### ISSUE THREAD

**Issue by rapidexpert** [womenhackfornonprofits/whfnp#48]
Since sponsors have been embedded into a singular image, I am unable to navigate to their website to find out more about them.

**Comment by tanyapowell** [comment]
@rapidexpert this wasn't a requirement for this project so I'll close this issue for now and if the stakeholders want to add this is the future we can re-open this

**Comment by tanyapowell** [comment]
@rapidexpert just realised this is not a singular image so will add the URLs for each partner to their image

**Comment by rapidexpert** [comment]
Thanks. Please let me know when it is live!
