### ISSUE TITLE
Changing project links to websites/appstore

### ISSUE THREAD

**Issue by rapidexpert** [womenhackfornonprofits/whfnp#52]
It may be more useful to potential clients to see the output rather than github code. It maybe that going forward we add a link to our websites to have stuff to fork the code..

**Comment by tanyapowell** [comment]
Probably worth having a link to the github repo AND the app store/website. So instead of: 
![image](https://cloud.githubusercontent.com/assets/11095605/15187270/637babd8-1798-11e6-8928-e1d99b3d7ff2.png)

Have two separate buttons like:
[view open source project](#) | [visit website ](#)

**Comment by EChesters** [comment]
Both buttons make sense. If we're prioritising clients over volunteers, then the website button should be on the right, keeping the code link on the left.

**Comment by Nandhini31** [comment]
I am happy to have both buttons (github and link)

**Comment by lili2311** [comment]
- unfinished projects do not have live website, those will only have one button still "View Open Source Project"?

**Comment by lili2311** [comment]
@laurentate will you be completing this issue? We are hoping to go live with release 2 end of October so need to try and finish up and test :)
