### ISSUE TITLE
Misleading text on Non-Profits page

### ISSUE THREAD

**Issue by EChesters** [womenhackfornonprofits/whfnp#58]
Under "Work With Us" it mentions to fill out a form below, but you're faced with a button which takes you to a different page which has the form on it. 

<img width="776" alt="screen shot 2016-04-19 at 11 17 13" src="https://cloud.githubusercontent.com/assets/2605703/14635893/4afe6246-0620-11e6-9cdf-04b9506de6eb.png">

On second thoughts, the form should just be on the page rather than on its own page.

The form needs to move onto the Non-Profits page under the "Work with us" section. The text will then not need changing because the form will actually be below the header.

**Comment by lili2311** [comment]
- the form has it's own page, will that still be needed or is the idea that the form only exists under this page now?

**Comment by rapidexpert** [comment]
It may be better on the same page, it takes two clicks to navigate to the form...not exactly one touch

**Comment by EChesters** [comment]
@rapidexpert This was mentioned in the very first post. This will be changed when this issue is picked up.

> On second thoughts, the form should just be on the page rather than on its own page.

**Comment by VAO11** [comment]
c9.io host and port added to the Gruntfile.js for contributors using c9.io hosting

Non-Profits Contact Form added to the Non-Profits.html page

![non-profit-contact-form_iss58](https://cloud.githubusercontent.com/assets/20387843/18166149/5c509d76-7041-11e6-9d2d-71c0942f73cb.PNG)

@EChesters @lili2311 @tanyapowell @krissy 

Please review the update and advise if you are happy for me to merge it to the dev branch.

Thanks,

Victoria

**Comment by lili2311** [comment]
Commented on PR @VAO11 :)

**Comment by VAO11** [comment]
New Branch Issue 58 #144 Merged Successfully
