### ISSUE TITLE
Change footer to match actual designs

### ISSUE THREAD

**Issue by EChesters** [womenhackfornonprofits/whfnp#59]
Replace footer with design and more information than copyright info. 

New footer will look like this:
<img width="1679" alt="screen shot 2016-04-19 at 14 32 55" src="https://cloud.githubusercontent.com/assets/2605703/14640897/a36d6146-063b-11e6-9b2f-26b822b38216.png">

**Comment by EChesters** [comment]
Don't merge for now, there's a second underline on link hovers and I can't find the bugger.

**Comment by tanyapowell** [comment]
@EChesters how will it look on mobile?

**Comment by EChesters** [comment]
It looks like this on mobile: 
<img width="465" alt="screen shot 2016-05-15 at 19 36 31" src="https://cloud.githubusercontent.com/assets/2605703/15276054/5fc6ddf2-1ad4-11e6-9794-cfcaf8efc4b6.png">

**Comment by EChesters** [comment]
This has been fixed by: https://github.com/womenhackfornonprofits/whfnp/commit/2e923ea442e1c6d857d0e64c3ee2cf4d7555113f#diff-339b0abafb73bbc22959362619d8b7dd
