### ISSUE TITLE
Replace banner images on Events and Contact Us page with higher res versions

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp#63]
### Events

![image](https://cloud.githubusercontent.com/assets/11095605/14672453/dfcc7410-06ef-11e6-927a-dad0882c972b.png)
### Contact Us

![image](https://cloud.githubusercontent.com/assets/11095605/14672472/f47dbaea-06ef-11e6-94d8-23de847293ff.png)

**Comment by lili2311** [comment]
@tanyapowell are these compressed please? In case they are not :D https://tinypng.com/

**Comment by tanyapowell** [comment]
They are currently uncompressed RAW images, so will be converting (without
losing too much data) anyway. Can do all the compression from within the
image management tool used for RAW conversions :)
