### ISSUE TITLE
New Contact Us Page

### ISSUE THREAD

**Issue by EChesters** [womenhackfornonprofits/whfnp#66]
The contact us page is very bare minimal, with nothing to entice you to contact us. It also doesn't point the user to contacting us in a very quick way - like Twitter or FB. 

Forms also need a makeover. Red needs to be reserved for errors, not example text. 

It's not shown which ones are required. We have no reason to ask for mobile number or make it required either.

**Comment by tanyapowell** [comment]
@Nandhini31 @khandelwalrinki on the contact us form can you confirm which fields are required?

**Comment by tanyapowell** [comment]
Also, @EChesters I'll create a new issue for this

> Forms also need a makeover. Red needs to be reserved for errors, not example text.

**Comment by Nandhini31** [comment]
Phone number is not required. Name,email and message are must for us to get back in touch with them.

**Comment by EChesters** [comment]
New form style proposed:

<img width="903" alt="screen shot 2016-06-19 at 20 03 28" src="https://cloud.githubusercontent.com/assets/2605703/16179312/032a5880-3659-11e6-808d-52c040677b50.png">

I've made it clear that phone is optional since it's off-putting seeing that data being asked.
Made the CTA a big longer and friendlier, using ! for enthusiasm. 
Also changed the Jon Snow character to be Ada Lovelace, she was the first famous woman in tech I could remember, and happy to change it if anyone's passionate about using someone specific.
