### ISSUE TITLE
Add Fashion Revolution to completed projects

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp#68]
This is a recently completed project and should be added to the projects page

**Comment by tanyapowell** [comment]
@womenhackfornonprofits/fashion-revolution-team can you please provide info for the **Fashion Revolution** project so we can update the projects page

**Comment by lili2311** [comment]
**Project** Name: Fashion Revolution Wall
**Technology**: Django, Python, HTML, Sass, JavaScript, Heroku
**Description**: Fashion Revolution raise awareness of the true cost of fashion and show that together we can create a more sustainable future for our fashion industry.
WHFNP volunteers built a Fashion revolution Wall Django app to help raise awareness during Fashion Revolution Week. The wall pulled in twitter images submissions via a given hashtag to create a submission wall.
**Url**: [fashrevwall.com](http://fashrevwall.com)

**Comment by tanyapowell** [comment]
@lili2311 can this issue be closed?
