### ISSUE TITLE
Outstanding copy changes

### ISSUE THREAD

**Issue by krissy** [womenhackfornonprofits/whfnp#8]
- [x] Update Projects section to correct copy. **Funmi to create a PR to merge into here**
- [x] About page: Our Mission section seems redundant - can we replace this with a How We Started/History section? **Blocker: board/web team to confirm**
- [ ] FAQ page: We mention non-profits don't join Slack, but we do have some non-profits in there. Can we clarify exceptions to this case? **Vinita / Nandhini to confirm**

cc @Nandhini31

**Comment by khandelwalrinki** [comment]
I agree we need to have some sort of guidelines around how we decide on non profits access to Slack. The way I was thinking is we give to individuals who also participate as volunteers even though they might also represent a non-profit.  Does that make sense?

**Comment by khandelwalrinki** [comment]
Also may be combine "Mission" last line with "Who are we?" - I really like the call for volunteer there and we can remove the rest? And then rename = "Who are we" to "Our Mission" or "What are we trying to do"? ..

**Comment by krissy** [comment]
Ta @khandelwalrinki! @lili2311 If we get rid of the Mission section on About page and merge into one section what UI tweaks need to be considered? (e.g. Board section now needs blue bg?)

**Comment by lili2311** [comment]
Board section will then become blue and the social icons will be white, so on other pages with this I have added newsletter signup at the bottom or something else like that to make sure last section is white.
Other option is not have coloured sections on this page and keep all white.

Also since the text is now longer it will definitely have to be not centered, will need to break down into paragraphs and probably alight left.

**Comment by lili2311** [comment]
Combined Who we are and our mission now, renamed as well in this [PR](https://github.com/womenhackfornonprofits/whfnp/pull/13)

**Comment by krissy** [comment]
Project copy addressed in https://github.com/womenhackfornonprofits/whfnp/issues/20, please review

**Comment by lili2311** [comment]
Do you have screenshots of what the Project page looks like now due to these changes?

**Comment by krissy** [comment]
@lili2311 
![image](https://cloud.githubusercontent.com/assets/574526/13109313/540096a6-d570-11e5-9a99-59e605bb145d.png)

![image](https://cloud.githubusercontent.com/assets/574526/13109325/6a342c08-d570-11e5-8868-d1dc69b3d991.png)

![image](https://cloud.githubusercontent.com/assets/574526/13109342/8d426764-d570-11e5-8f34-0a79302cb911.png)

**Comment by lili2311** [comment]
Okay they are all too long now for the picture I will have to increase the Project Picture height as well.

**Comment by lili2311** [comment]
:+1:
