### ISSUE TITLE
Contradictory Tech Stack for Pimp project

### ISSUE THREAD

**Issue by tanyapowell** [womenhackfornonprofits/whfnp#97]
In the tech stack list it doesn't mention PHP, but it says the team are using PHP in the second paragraph

![image](https://cloud.githubusercontent.com/assets/11095605/15275915/3de45b14-1ad0-11e6-8bf7-e1361a1b0017.png)

**Comment by lili2311** [comment]
Tech stack completely changed now :D Will update
